# Defaults based on the opennmt-defaults.yml config
# of the OpenNMT-tf repository (MIT License):
# https://github.com/OpenNMT/OpenNMT-tf

params:
  optimizer: GradientDescentOptimizer
  learning_rate: 0.8
  param_init: 0.1
  clip_gradients: 5.0
  decay_type: exponential_decay
  decay_rate: 0.7
  decay_steps: 100000
  start_decay_steps: 500000
  beam_width: 5
  maximum_iterations: 250

train:
  batch_size: 64
  bucket_width: 1
  save_checkpoints_steps: 5000
  save_summary_steps: 50
  train_steps: 15000 # More steps will give a better model but take longer to train
  maximum_features_length: 50
  maximum_labels_length: 50
  sample_buffer_size: 1000000  # Consider setting this to the training dataset size.

eval:
  eval_delay: 18000  # Every 5 hours.

infer:
  batch_size: 30


# Data definitions

model_dir: bot/models/chat

data:
  train_features_file: bot/chat-data/src-train.txt
  train_labels_file: bot/chat-data/tgt-train.txt
  eval_features_file: bot/chat-data/src-val.txt
  eval_labels_file: bot/chat-data/tgt-val.txt
  source_words_vocabulary: bot/chat-data/src-vocab.txt
  target_words_vocabulary: bot/chat-data/tgt-vocab.txt

